import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  Modal,
  ScrollView,
  TouchableOpacity,
} from 'react-native';
import { ShieldCheck, Scale, Lock, IndianRupee, CheckCircle2, X } from 'lucide-react-native';

interface LegalComplianceModalProps {
  visible: boolean;
  onClose: () => void;
  initialTab?: 'gst' | 'payments' | 'terms' | 'privacy';
}

export const LegalComplianceModal: React.FC<LegalComplianceModalProps> = ({
  visible,
  onClose,
  initialTab = 'gst',
}) => {
  const [activeTab, setActiveTab] = useState<'gst' | 'payments' | 'terms' | 'privacy'>(initialTab);

  return (
    <Modal visible={visible} animationType="slide" transparent onRequestClose={onClose}>
      <View style={styles.modalOverlay}>
        <View style={styles.modalContainer}>
          {/* Header */}
          <View style={styles.header}>
            <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}>
              <View style={styles.iconWrap}>
                <Scale size={20} color="#ffffff" />
              </View>
              <View style={{ flex: 1 }}>
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}>
                  <Text style={styles.headerTitle}>Legal & Statutory Compliance</Text>
                </View>
                <Text style={styles.headerSub}>CGST Rules 2017 • IT Act 2000 • DPDP 2023</Text>
              </View>
            </View>
            <TouchableOpacity onPress={onClose} style={styles.closeBtn}>
              <X size={18} color="#64748b" />
            </TouchableOpacity>
          </View>

          {/* Tabs */}
          <View style={styles.tabsRow}>
            <TouchableOpacity
              onPress={() => setActiveTab('gst')}
              style={[styles.tabBtn, activeTab === 'gst' && styles.tabBtnActive]}
            >
              <Text style={[styles.tabText, activeTab === 'gst' && styles.tabTextActive]}>🧾 GST 46</Text>
            </TouchableOpacity>
            <TouchableOpacity
              onPress={() => setActiveTab('payments')}
              style={[styles.tabBtn, activeTab === 'payments' && styles.tabBtnActive]}
            >
              <Text style={[styles.tabText, activeTab === 'payments' && styles.tabTextActive]}>💳 Payments</Text>
            </TouchableOpacity>
            <TouchableOpacity
              onPress={() => setActiveTab('privacy')}
              style={[styles.tabBtn, activeTab === 'privacy' && styles.tabBtnActive]}
            >
              <Text style={[styles.tabText, activeTab === 'privacy' && styles.tabTextActive]}>🔒 DPDP</Text>
            </TouchableOpacity>
            <TouchableOpacity
              onPress={() => setActiveTab('terms')}
              style={[styles.tabBtn, activeTab === 'terms' && styles.tabBtnActive]}
            >
              <Text style={[styles.tabText, activeTab === 'terms' && styles.tabTextActive]}>📜 Terms</Text>
            </TouchableOpacity>
          </View>

          {/* Tab Content */}
          <ScrollView style={styles.body} showsVerticalScrollIndicator={false}>
            {activeTab === 'gst' && (
              <View style={styles.sectionWrap}>
                <View style={styles.badgeBanner}>
                  <CheckCircle2 size={16} color="#059669" />
                  <Text style={styles.badgeBannerText}>Rule 46 CGST Rules, 2017 Compliant</Text>
                </View>
                <Text style={styles.para}>
                  All tax invoices generated by KwikBill Pro comply with the 16 statutory particulars mandated by the Central Board of Indirect Taxes & Customs (CBIC).
                </Text>
                <View style={styles.bulletCard}>
                  <Text style={styles.bulletItem}>• 15-Digit Supplier & Client GSTIN validation</Text>
                  <Text style={styles.bulletItem}>• Sequential Invoice Number (≤16 characters per FY)</Text>
                  <Text style={styles.bulletItem}>• 2-Digit Place of Supply & Official State Codes</Text>
                  <Text style={styles.bulletItem}>• Itemized HSN/SAC & CGST+SGST vs IGST split</Text>
                  <Text style={styles.bulletItem}>• Reverse Charge (RCM) declaration</Text>
                  <Text style={styles.bulletItem}>• Digital validity under Section 65B of Indian Evidence Act</Text>
                </View>
              </View>
            )}

            {activeTab === 'payments' && (
              <View style={styles.sectionWrap}>
                <View style={[styles.badgeBanner, { backgroundColor: '#e0e7ff', borderColor: '#c7d2fe' }]}>
                  <IndianRupee size={16} color="#4338ca" />
                  <Text style={[styles.badgeBannerText, { color: '#312e81' }]}>NPCI Direct UPI Settlement Protocol</Text>
                </View>
                <Text style={styles.para}>
                  KwikBill Pro facilitates direct peer-to-merchant UPI payments. All dynamic QR codes use official NPCI deep-linking parameters (<Text style={{ fontFamily: 'monospace' }}>upi://pay?pa=...&am=...</Text>).
                </Text>
                <View style={styles.bulletCard}>
                  <Text style={styles.bulletItem}>• 100% Direct bank-to-bank settlement (Zero Escrow)</Text>
                  <Text style={styles.bulletItem}>• No intermediate pooling of customer funds</Text>
                  <Text style={styles.bulletItem}>• Operates as pure SaaS (RBI PA License Exempt)</Text>
                </View>
              </View>
            )}

            {activeTab === 'privacy' && (
              <View style={styles.sectionWrap}>
                <View style={[styles.badgeBanner, { backgroundColor: '#fef3c7', borderColor: '#fde68a' }]}>
                  <Lock size={16} color="#b45309" />
                  <Text style={[styles.badgeBannerText, { color: '#78350f' }]}>Digital Personal Data Protection Act, 2023</Text>
                </View>
                <Text style={styles.para}>
                  We implement enterprise-grade encryption and strict purpose limitation in accordance with Indian DPDP Act 2023 principles.
                </Text>
                <View style={styles.bulletCard}>
                  <Text style={styles.bulletItem}>• Customer financial & contact data is 100% confidential</Text>
                  <Text style={styles.bulletItem}>• Zero third-party data selling or monetization</Text>
                  <Text style={styles.bulletItem}>• Right to data export and complete account deletion</Text>
                </View>
              </View>
            )}

            {activeTab === 'terms' && (
              <View style={styles.sectionWrap}>
                <View style={[styles.badgeBanner, { backgroundColor: '#f1f5f9', borderColor: '#e2e8f0' }]}>
                  <ShieldCheck size={16} color="#334155" />
                  <Text style={[styles.badgeBannerText, { color: '#0f172a' }]}>SaaS Service Terms & Limitation of Liability</Text>
                </View>
                <Text style={styles.para}>
                  KwikBill Pro provides billing and payment automation software. Users remain responsible for timely filing of GSTR-1 and GSTR-3B tax returns.
                </Text>
                <View style={styles.bulletCard}>
                  <Text style={styles.bulletItem}>• Software utility for invoicing, receivables & payment QR</Text>
                  <Text style={styles.bulletItem}>• Automated WhatsApp reminders strictly for legitimate dues</Text>
                  <Text style={styles.bulletItem}>• 15-day free trial with monthly/annual SaaS subscriptions</Text>
                </View>
              </View>
            )}
          </ScrollView>

          {/* Close Action */}
          <View style={styles.footer}>
            <TouchableOpacity onPress={onClose} style={styles.footerBtn}>
              <Text style={styles.footerBtnText}>Acknowledge & Close</Text>
            </TouchableOpacity>
          </View>
        </View>
      </View>
    </Modal>
  );
};

const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.7)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: '85%',
    paddingBottom: 24,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  iconWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#4f46e5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 15,
    fontWeight: '900',
    color: '#0f172a',
  },
  headerSub: {
    fontSize: 10.5,
    color: '#64748b',
    marginTop: 2,
  },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabsRow: {
    flexDirection: 'row',
    backgroundColor: '#f8fafc',
    paddingHorizontal: 16,
    paddingTop: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    gap: 8,
  },
  tabBtn: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabBtnActive: {
    borderBottomColor: '#4f46e5',
  },
  tabText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748b',
  },
  tabTextActive: {
    color: '#4f46e5',
  },
  body: {
    padding: 20,
  },
  sectionWrap: {
    gap: 12,
  },
  badgeBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#ecfdf5',
    borderWidth: 1,
    borderColor: '#a7f3d0',
    padding: 12,
    borderRadius: 14,
  },
  badgeBannerText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#065f46',
  },
  para: {
    fontSize: 12.5,
    color: '#475569',
    lineHeight: 18,
  },
  bulletCard: {
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 14,
    padding: 14,
    gap: 8,
  },
  bulletItem: {
    fontSize: 12,
    color: '#334155',
    lineHeight: 16,
  },
  footer: {
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  footerBtn: {
    backgroundColor: '#4f46e5',
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: 'center',
  },
  footerBtnText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#ffffff',
  },
});
