import React, { useState, useEffect, useCallback } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  RefreshControl,
  ActivityIndicator,
  Alert,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import {
  Repeat,
  Calendar,
  IndianRupee,
  Play,
  Pause,
  Plus,
  Zap,
  ArrowLeft,
  Sparkles,
  CheckCircle2,
  AlertCircle,
  MessageSquare,
} from 'lucide-react-native';
import { api } from '../api/endpoints.ts';
import { RecurringProfile } from '../types/index.ts';
import { useMobileAuth } from '../context/AuthContext.tsx';
import { getPlanLimits } from '../utils/planConfig.ts';

export const RecurringScreen: React.FC<{ navigation: any }> = ({ navigation }) => {
  const { user } = useMobileAuth();
  const planLimits = getPlanLimits(user);
  const isPro = planLimits.canUseRecurringBilling;
  const [profiles, setProfiles] = useState<RecurringProfile[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [isTriggering, setIsTriggering] = useState(false);

  const loadData = useCallback(async () => {
    try {
      const data = await api.getRecurringProfiles();
      if (Array.isArray(data)) {
        setProfiles(data);
      }
    } catch (err: any) {
      console.log('Error loading recurring schedules:', err);
    } finally {
      setIsLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => {
    loadData();
  }, [loadData]);

  const onRefresh = () => {
    setRefreshing(true);
    loadData();
  };

  const handleToggle = async (id: number) => {
    try {
      await api.toggleRecurringProfile(id);
      loadData();
    } catch (err: any) {
      Alert.alert('Error', err.message || 'Failed to toggle status');
    }
  };

  const handleRunNow = async () => {
    setIsTriggering(true);
    try {
      const res = await api.triggerManualRecurringRun();
      Alert.alert(
        'Auto-Billing Scan Complete',
        `Generated ${res?.result?.count || 0} scheduled invoices successfully!`
      );
      loadData();
    } catch (err: any) {
      Alert.alert('Scan Result', err.message || 'Auto-billing scan completed');
    } finally {
      setIsTriggering(false);
    }
  };

  const activeProfiles = profiles.filter((p) => p.isActive);
  const totalMonthlyRunRate = profiles.reduce((sum, p) => {
    if (!p.isActive) return sum;
    const amt = parseFloat(p.totalAmount || '0');
    if (p.frequency === 'weekly') return sum + amt * 4;
    if (p.frequency === 'monthly') return sum + amt;
    if (p.frequency === 'quarterly') return sum + amt / 3;
    if (p.frequency === 'yearly') return sum + amt / 12;
    return sum + amt;
  }, 0);

  const totalAutoGeneratedCount = profiles.reduce(
    (sum, p) => sum + (p.generatedCount || 0),
    0
  );

  return (
    <View style={styles.container}>
      <ScrollView
        contentContainerStyle={styles.scrollContent}
        refreshControl={
          <RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor="#4f46e5" />
        }
        showsVerticalScrollIndicator={false}
      >
        {/* Full Bleed Hero Header */}
        <LinearGradient
          colors={['#0f172a', '#1e1b4b', '#312e81']}
          start={{ x: 0, y: 0 }}
          end={{ x: 1, y: 1 }}
          style={styles.heroHeader}
        >
          <View style={styles.heroTopRow}>
            <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}>
              <TouchableOpacity
                onPress={() => navigation.goBack()}
                style={styles.backBtn}
                activeOpacity={0.8}
              >
                <ArrowLeft size={18} color="#ffffff" />
              </TouchableOpacity>
              <View>
                <Text style={styles.heroSubText}>AUTOPILOT REVENUE</Text>
                <Text style={styles.heroTitle}>Recurring Invoices</Text>
              </View>
            </View>
            <View style={styles.heroGstPill}>
              <Sparkles size={11} color="#34d399" />
              <Text style={styles.heroGstText}>CRON ACTIVE</Text>
            </View>
          </View>

          {/* Quick Metrics Bar */}
          <View style={styles.heroStatsBox}>
            <View style={styles.heroStatItem}>
              <Text style={styles.heroStatLabel}>MONTHLY RUN RATE</Text>
              <Text style={styles.heroStatVal}>
                ₹{Math.round(totalMonthlyRunRate).toLocaleString('en-IN')}
              </Text>
            </View>
            <View style={styles.heroStatDivider} />
            <View style={styles.heroStatItem}>
              <Text style={styles.heroStatLabel}>ACTIVE SCHEDULES</Text>
              <Text style={styles.heroStatVal}>
                {activeProfiles.length} <Text style={styles.heroStatSub}>/ {profiles.length}</Text>
              </Text>
            </View>
          </View>
        </LinearGradient>

        {/* PRO PLAN RESTRICTION BANNER IF NOT PRO */}
        {!isPro && (
          <View style={styles.proLockCard}>
            <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 4 }}>
              <Sparkles size={16} color="#c084fc" />
              <Text style={styles.proLockTitle}>PRO PLAN FEATURE: AUTO-BILLING</Text>
            </View>
            <Text style={styles.proLockDesc}>
              Automated recurring billing schedules and automatic WhatsApp alerts are exclusive to the Pro Growth Plan (₹499/mo).
            </Text>
            <TouchableOpacity
              style={styles.proUpgradeBtn}
              onPress={() => navigation.navigate('Settings')}
              activeOpacity={0.85}
            >
              <Text style={styles.proUpgradeText}>Upgrade to Pro in Settings (₹499/mo)</Text>
            </TouchableOpacity>
          </View>
        )}

        {/* Action Trigger Buttons */}
        <View style={styles.actionRow}>
          <TouchableOpacity
            style={styles.runScanBtn}
            onPress={handleRunNow}
            disabled={isTriggering}
            activeOpacity={0.85}
          >
            {isTriggering ? (
              <ActivityIndicator size="small" color="#4f46e5" />
            ) : (
              <>
                <Zap size={14} color="#4f46e5" />
                <Text style={styles.runScanText}>Run Auto-Billing Scan</Text>
              </>
            )}
          </TouchableOpacity>

          <TouchableOpacity
            style={styles.createBtn}
            onPress={() => navigation.navigate('InvoiceCreate')}
            activeOpacity={0.85}
          >
            <Plus size={14} color="#ffffff" strokeWidth={2.5} />
            <Text style={styles.createText}>+ New Schedule</Text>
          </TouchableOpacity>
        </View>

        {/* Schedules List Section */}
        <View style={styles.sectionHeader}>
          <Text style={styles.sectionTitle}>Active Contracts & Retainers</Text>
          <Text style={styles.sectionBadge}>{profiles.length} Total</Text>
        </View>

        {isLoading ? (
          <View style={styles.loadingBox}>
            <ActivityIndicator size="large" color="#4f46e5" />
            <Text style={styles.loadingText}>Loading recurring billing contracts...</Text>
          </View>
        ) : profiles.length === 0 ? (
          <View style={styles.emptyCard}>
            <Repeat size={32} color="#cbd5e1" />
            <Text style={styles.emptyTitle}>No Recurring Contracts Set Up</Text>
            <Text style={styles.emptySub}>
              Create retainer or monthly billing schedules to auto-issue invoices and send WhatsApp reminders on autopilot.
            </Text>
            <TouchableOpacity
              style={styles.emptyCreateBtn}
              onPress={() => navigation.navigate('InvoiceCreate')}
            >
              <Plus size={14} color="#ffffff" strokeWidth={2.5} />
              <Text style={styles.emptyCreateText}>Create First Schedule</Text>
            </TouchableOpacity>
          </View>
        ) : (
          profiles.map((p) => {
            return (
              <View key={p.id} style={styles.profileCard}>
                <View style={styles.cardTopRow}>
                  <View style={{ flex: 1, marginRight: 10 }}>
                    <Text style={styles.profileTitle} numberOfLines={1}>
                      {p.title}
                    </Text>
                    <Text style={styles.profileClient} numberOfLines={1}>
                      {p.client?.name || 'Client'} {p.client?.businessName ? `(${p.client.businessName})` : ''}
                    </Text>

                  </View>
                  <View
                    style={[
                      styles.statusPill,
                      p.isActive ? styles.statusActive : styles.statusPaused,
                    ]}
                  >
                    <Text
                      style={[
                        styles.statusText,
                        p.isActive ? styles.statusTextActive : styles.statusTextPaused,
                      ]}
                    >
                      {p.isActive ? 'ACTIVE' : 'PAUSED'}
                    </Text>
                  </View>
                </View>

                <View style={styles.cardDivider} />

                <View style={styles.cardMetaRow}>
                  <View>
                    <Text style={styles.metaLabel}>AMOUNT / CYCLE</Text>
                    <Text style={styles.metaAmount}>
                      ₹{parseFloat(p.totalAmount).toLocaleString('en-IN')}
                    </Text>
                  </View>

                  <View>
                    <Text style={styles.metaLabel}>FREQUENCY</Text>
                    <View style={styles.freqBadge}>
                      <Text style={styles.freqText}>{p.frequency.toUpperCase()}</Text>
                    </View>
                  </View>

                  <View>
                    <Text style={styles.metaLabel}>NEXT INVOICE</Text>
                    <View style={styles.dateRow}>
                      <Calendar size={12} color="#4f46e5" />
                      <Text style={styles.dateText}>{p.nextRunDate}</Text>
                    </View>
                  </View>
                </View>

                {/* Card Footer Controls */}
                <View style={styles.cardFooter}>
                  <View style={styles.generatedBadge}>
                    <Text style={styles.generatedText}>
                      Auto-Billed: <Text style={{ fontWeight: '900', color: '#0f172a' }}>{p.generatedCount} invoices</Text>
                    </Text>
                  </View>

                  <TouchableOpacity
                    style={[
                      styles.toggleBtn,
                      p.isActive ? styles.toggleBtnPause : styles.toggleBtnResume,
                    ]}
                    onPress={() => handleToggle(p.id)}
                    activeOpacity={0.8}
                  >
                    {p.isActive ? (
                      <>
                        <Pause size={12} color="#b45309" />
                        <Text style={styles.toggleTextPause}>Pause</Text>
                      </>
                    ) : (
                      <>
                        <Play size={12} color="#059669" />
                        <Text style={styles.toggleTextResume}>Resume</Text>
                      </>
                    )}
                  </TouchableOpacity>
                </View>
              </View>
            );
          })
        )}
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  scrollContent: {
    paddingBottom: 40,
  },
  heroHeader: {
    paddingHorizontal: 20,
    paddingTop: 48,
    paddingBottom: 22,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    marginBottom: 16,
    shadowColor: '#1e1b4b',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  heroSubText: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#818cf8',
    letterSpacing: 1,
  },
  heroTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#ffffff',
    marginTop: 2,
    letterSpacing: -0.3,
  },
  heroGstPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
  },
  heroGstText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#34d399',
    letterSpacing: 0.5,
  },
  heroStatsBox: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  heroStatItem: {
    flex: 1,
    alignItems: 'center',
  },
  heroStatDivider: {
    width: 1,
    height: 28,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
  },
  heroStatLabel: {
    fontSize: 9,
    fontWeight: '800',
    color: '#a5b4fc',
    letterSpacing: 0.5,
  },
  heroStatVal: {
    fontSize: 17,
    fontWeight: '900',
    color: '#ffffff',
    marginTop: 2,
  },
  heroStatSub: {
    fontSize: 11,
    color: '#94a3b8',
    fontWeight: '600',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  runScanBtn: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: '#c7d2fe',
    shadowColor: '#4f46e5',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 1,
  },
  runScanText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#4f46e5',
  },
  createBtn: {
    flex: 1,
    backgroundColor: '#4f46e5',
    borderRadius: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    shadowColor: '#4f46e5',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  createText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#ffffff',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 14.5,
    fontWeight: '900',
    color: '#0f172a',
  },
  sectionBadge: {
    fontSize: 10,
    fontWeight: '800',
    color: '#64748b',
    backgroundColor: '#e2e8f0',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
  },
  loadingBox: {
    padding: 30,
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 12,
    color: '#64748b',
    fontWeight: '600',
    marginTop: 8,
  },
  emptyCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    marginHorizontal: 16,
    padding: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  emptyTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#334155',
    marginTop: 10,
  },
  proLockCard: {
    marginHorizontal: 16,
    marginTop: 12,
    padding: 14,
    backgroundColor: '#1e1b4b',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#7c3aed',
  },
  proLockTitle: {
    fontSize: 11,
    fontWeight: '900',
    color: '#e9d5ff',
    letterSpacing: 0.5,
  },
  proLockDesc: {
    fontSize: 11,
    color: '#c7d2fe',
    lineHeight: 16,
    marginBottom: 10,
  },
  proUpgradeBtn: {
    backgroundColor: '#7c3aed',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  proUpgradeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#ffffff',
  },
  emptySub: {
    fontSize: 11.5,
    color: '#94a3b8',
    textAlign: 'center',
    marginTop: 4,
    lineHeight: 17,
  },
  emptyCreateBtn: {
    backgroundColor: '#4f46e5',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    marginTop: 14,
  },
  emptyCreateText: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#ffffff',
  },
  profileCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  cardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  profileTitle: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#0f172a',
  },
  profileClient: {
    fontSize: 11.5,
    color: '#475569',
    marginTop: 2,
    fontWeight: '600',
  },
  statusPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  statusActive: {
    backgroundColor: '#ecfdf5',
  },
  statusPaused: {
    backgroundColor: '#fffbeb',
  },
  statusText: {
    fontSize: 9.5,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  statusTextActive: {
    color: '#059669',
  },
  statusTextPaused: {
    color: '#d97706',
  },
  cardDivider: {
    height: 1,
    backgroundColor: '#f1f5f9',
    marginVertical: 12,
  },
  cardMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  metaLabel: {
    fontSize: 8.5,
    fontWeight: '800',
    color: '#94a3b8',
    letterSpacing: 0.5,
    marginBottom: 3,
  },
  metaAmount: {
    fontSize: 15,
    fontWeight: '900',
    color: '#0f172a',
  },
  freqBadge: {
    backgroundColor: '#eef2ff',
    paddingHorizontal: 7,
    paddingVertical: 2.5,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#c7d2fe',
  },
  freqText: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#4f46e5',
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  dateText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#334155',
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#f8fafc',
  },
  generatedBadge: {
    backgroundColor: '#f8fafc',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  generatedText: {
    fontSize: 10,
    color: '#64748b',
    fontWeight: '600',
  },
  toggleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
  },
  toggleBtnPause: {
    backgroundColor: '#fffbeb',
    borderColor: '#fde68a',
  },
  toggleBtnResume: {
    backgroundColor: '#ecfdf5',
    borderColor: '#a7f3d0',
  },
  toggleTextPause: {
    fontSize: 10,
    fontWeight: '800',
    color: '#b45309',
  },
  toggleTextResume: {
    fontSize: 10,
    fontWeight: '800',
    color: '#059669',
  },
});
