import React, { useState, useEffect } from 'react';
import {
  Repeat,
  Calendar,
  IndianRupee,
  Clock,
  Play,
  Pause,
  Trash2,
  Plus,
  CheckCircle2,
  AlertCircle,
  MessageSquare,
  Sparkles,
  RefreshCw,
  Zap,
  ArrowUpRight
} from 'lucide-react';
import { RecurringProfile, Client } from '../lib/types.ts';
import {
  fetchRecurringProfiles,
  toggleRecurringProfile,
  deleteRecurringProfile,
  triggerManualRecurringRun
} from '../lib/api.ts';

interface RecurringInvoicesViewProps {
  clients: Client[];
  onCreateRecurring: () => void;
}

export const RecurringInvoicesView: React.FC<RecurringInvoicesViewProps> = ({
  clients,
  onCreateRecurring,
}) => {
  const [profiles, setProfiles] = useState<RecurringProfile[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isTriggering, setIsTriggering] = useState(false);
  const [triggerMessage, setTriggerMessage] = useState<string | null>(null);

  const loadData = async () => {
    setIsLoading(true);
    try {
      const res = await fetchRecurringProfiles();
      if (res.success && Array.isArray(res.profiles)) {
        setProfiles(res.profiles);
      }
    } catch (err) {
      console.error('Error fetching recurring profiles:', err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  const handleToggle = async (id: number) => {
    try {
      await toggleRecurringProfile(id);
      loadData();
    } catch (err: any) {
      alert(err.message || 'Failed to update schedule status');
    }
  };

  const handleDelete = async (id: number) => {
    if (!confirm('Are you sure you want to stop and delete this recurring billing profile?')) return;
    try {
      await deleteRecurringProfile(id);
      loadData();
    } catch (err: any) {
      alert(err.message || 'Failed to delete recurring profile');
    }
  };

  const handleManualRunNow = async () => {
    setIsTriggering(true);
    setTriggerMessage(null);
    try {
      const res = await triggerManualRecurringRun();
      if (res.success && res.result) {
        setTriggerMessage(`✅ Generated ${res.result.count} due invoices successfully!`);
        loadData();
      }
    } catch (err: any) {
      setTriggerMessage(`❌ ${err.message || 'Failed to execute auto-billing scan'}`);
    } finally {
      setIsTriggering(false);
    }
  };

  // Metrics
  const activeCount = profiles.filter((p) => p.isActive).length;
  const totalMonthlyRunRate = profiles.reduce((sum, p) => {
    if (!p.isActive) return sum;
    const amt = parseFloat(p.totalAmount || '0');
    if (p.frequency === 'weekly') return sum + amt * 4;
    if (p.frequency === 'monthly') return sum + amt;
    if (p.frequency === 'quarterly') return sum + amt / 3;
    if (p.frequency === 'yearly') return sum + amt / 12;
    return sum + amt;
  }, 0);

  const totalAutoGeneratedCount = profiles.reduce((sum, p) => sum + (p.generatedCount || 0), 0);

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="bg-slate-900 text-white p-6 rounded-3xl shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-indigo-500/20 text-indigo-300 text-xs font-bold border border-indigo-500/30 mb-2">
            <Repeat className="w-3.5 h-3.5" />
            <span>Automated Contract & Retainer Billing</span>
          </div>
          <h1 className="text-2xl font-black tracking-tight text-white">
            Recurring Invoices & Auto-Billing Engine
          </h1>
          <p className="text-sm text-slate-400 mt-1">
            Auto-generate GST tax invoices on a recurring schedule (Weekly, Monthly, Quarterly) and notify clients on WhatsApp without lifting a finger.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={handleManualRunNow}
            disabled={isTriggering}
            id="recurring-run-now-btn"
            className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 font-bold text-xs border border-slate-700 transition-all cursor-pointer disabled:opacity-50"
          >
            <Zap className={`w-4 h-4 text-amber-400 ${isTriggering ? 'animate-bounce' : ''}`} />
            <span>{isTriggering ? 'Running Scan...' : 'Run Auto-Billing Now'}</span>
          </button>

          <button
            onClick={onCreateRecurring}
            id="recurring-create-schedule-btn"
            className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs shadow-sm shadow-indigo-600/30 transition-all hover:scale-[1.02] cursor-pointer"
          >
            <Plus className="w-4 h-4" />
            <span>+ New Recurring Schedule</span>
          </button>
        </div>
      </div>

      {triggerMessage && (
        <div className="p-4 rounded-2xl bg-indigo-50 border border-indigo-200 text-indigo-900 text-xs font-semibold flex items-center justify-between">
          <span>{triggerMessage}</span>
          <button onClick={() => setTriggerMessage(null)} className="text-indigo-600 font-bold hover:underline">
            Dismiss
          </button>
        </div>
      )}

      {/* KPI Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div className="bg-white dark:bg-slate-900 p-5 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-xs flex items-center justify-between">
          <div>
            <div className="text-xs font-bold text-slate-500 uppercase tracking-wider">Predictable Monthly Inflow</div>
            <div className="text-2xl font-black text-slate-900 dark:text-white mt-1 font-mono text-emerald-600">
              ₹{Math.round(totalMonthlyRunRate).toLocaleString('en-IN')}
            </div>
            <div className="text-[11px] text-slate-400 dark:text-slate-500 mt-0.5">Calculated active monthly contract value</div>
          </div>
          <div className="w-12 h-12 rounded-2xl bg-emerald-50 text-emerald-600 flex items-center justify-center">
            <IndianRupee className="w-6 h-6" />
          </div>
        </div>

        <div className="bg-white dark:bg-slate-900 p-5 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-xs flex items-center justify-between">
          <div>
            <div className="text-xs font-bold text-slate-500 uppercase tracking-wider">Active Billing Schedules</div>
            <div className="text-2xl font-black text-slate-900 dark:text-white mt-1 font-mono text-indigo-600">
              {activeCount} <span className="text-slate-400 text-sm font-normal">/ {profiles.length} total</span>
            </div>
            <div className="text-[11px] text-slate-400 dark:text-slate-500 mt-0.5">Contracts currently generating invoices</div>
          </div>
          <div className="w-12 h-12 rounded-2xl bg-indigo-50 text-indigo-600 flex items-center justify-center">
            <Repeat className="w-6 h-6" />
          </div>
        </div>

        <div className="bg-white dark:bg-slate-900 p-5 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-xs flex items-center justify-between">
          <div>
            <div className="text-xs font-bold text-slate-500 uppercase tracking-wider">Auto-Invoices Generated</div>
            <div className="text-2xl font-black text-slate-900 dark:text-white mt-1 font-mono text-slate-800 dark:text-slate-200">
              {totalAutoGeneratedCount}
            </div>
            <div className="text-[11px] text-slate-400 dark:text-slate-500 mt-0.5">Dispatched automatically by backend engine</div>
          </div>
          <div className="w-12 h-12 rounded-2xl bg-amber-50 text-amber-600 flex items-center justify-center">
            <Sparkles className="w-6 h-6" />
          </div>
        </div>
      </div>

      {/* Recurring Schedules Table */}
      <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-xs overflow-hidden">
        <div className="p-5 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between">
          <div>
            <h2 className="text-sm font-bold text-slate-900 dark:text-white">Active Auto-Billing Contracts & Schedules</h2>
            <p className="text-xs text-slate-500 dark:text-slate-400">Invoices are automatically created and scheduled for collection</p>
          </div>
          <button
            onClick={loadData}
            className="p-2 rounded-xl text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800 transition"
            title="Refresh"
          >
            <RefreshCw className={`w-4 h-4 ${isLoading ? 'animate-spin' : ''}`} />
          </button>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-slate-50 text-slate-500 font-bold border-b border-slate-200 dark:border-slate-800 uppercase tracking-wider text-[11px]">
              <tr>
                <th className="py-3 px-4">Contract / Title</th>
                <th className="py-3 px-4">Client & Contact</th>
                <th className="py-3 px-4">Frequency</th>
                <th className="py-3 px-4">Amount</th>
                <th className="py-3 px-4">Next Invoice Date</th>
                <th className="py-3 px-4">Auto-WhatsApp</th>
                <th className="py-3 px-4">Status</th>
                <th className="py-3 px-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
              {profiles.length === 0 ? (
                <tr>
                  <td colSpan={8} className="py-12 text-center text-slate-400">
                    <Repeat className="w-8 h-8 text-slate-300 mx-auto mb-2" />
                    <p className="font-semibold text-slate-600">No Recurring Schedules Configured</p>
                    <p className="text-[11px] text-slate-400 mt-1">
                      Set up weekly, monthly, or retainer billing contracts for your repeat clients.
                    </p>
                    <button
                      onClick={onCreateRecurring}
                      className="mt-4 inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-indigo-600 text-white font-bold text-xs hover:bg-indigo-700 transition"
                    >
                      <Plus className="w-3.5 h-3.5" />
                      Create First Recurring Schedule
                    </button>
                  </td>
                </tr>
              ) : (
                profiles.map((p) => {
                  return (
                    <tr key={p.id} className="hover:bg-slate-50/80 dark:hover:bg-slate-800/40 transition-colors">
                      <td className="py-3.5 px-4">
                        <div className="font-bold text-slate-900 dark:text-white">{p.title}</div>
                        <div className="text-[10px] text-slate-400 dark:text-slate-500 mt-0.5">
                          Generated: <strong className="text-slate-700 dark:text-slate-300 font-mono">{p.generatedCount} invoices</strong>
                        </div>
                      </td>

                      <td className="py-3.5 px-4">
                        <div className="font-semibold text-slate-800 dark:text-slate-200">{p.client?.name}</div>
                        {p.client?.companyName && (
                          <div className="text-[10px] text-slate-500">{p.client.companyName}</div>
                        )}
                        <div className="text-[10px] text-slate-400 font-mono">+91 {p.client?.phone}</div>
                      </td>

                      <td className="py-3.5 px-4">
                        <span className="px-2.5 py-1 rounded-lg text-xs font-bold bg-indigo-50 dark:bg-indigo-950/60 text-indigo-700 dark:text-indigo-300 border border-indigo-200 dark:border-indigo-800 uppercase tracking-wider">
                          {p.frequency}
                        </span>
                      </td>

                      <td className="py-3.5 px-4 font-mono font-black text-slate-900 dark:text-white text-sm">
                        ₹{parseFloat(p.totalAmount).toLocaleString('en-IN')}
                      </td>

                      <td className="py-3.5 px-4">
                        <div className="font-mono font-bold text-indigo-600 flex items-center gap-1">
                          <Calendar className="w-3.5 h-3.5" />
                          <span>{p.nextRunDate}</span>
                        </div>
                        <div className="text-[10px] text-slate-400">Started: {p.startDate}</div>
                      </td>

                      <td className="py-3.5 px-4">
                        {p.autoSendWhatsApp ? (
                          <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-50 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-800">
                            <MessageSquare className="w-3 h-3 text-emerald-600" /> Enabled
                          </span>
                        ) : (
                          <span className="text-[10px] text-slate-400">Disabled</span>
                        )}
                      </td>

                      <td className="py-3.5 px-4">
                        <span
                          className={`px-2 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider ${
                            p.isActive
                              ? 'bg-emerald-100 text-emerald-800'
                              : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400'
                          }`}
                        >
                          {p.isActive ? 'Active' : 'Paused'}
                        </span>
                      </td>

                      <td className="py-3.5 px-4 text-right">
                        <div className="inline-flex items-center gap-2">
                          <button
                            onClick={() => handleToggle(p.id)}
                            className={`p-1.5 rounded-lg border transition ${
                              p.isActive
                                ? 'bg-amber-50 text-amber-700 border-amber-200 hover:bg-amber-100'
                                : 'bg-emerald-50 text-emerald-700 border-emerald-200 hover:bg-emerald-100'
                            }`}
                            title={p.isActive ? 'Pause Schedule' : 'Resume Schedule'}
                          >
                            {p.isActive ? <Pause className="w-3.5 h-3.5" /> : <Play className="w-3.5 h-3.5" />}
                          </button>

                          <button
                            onClick={() => handleDelete(p.id)}
                            className="p-1.5 rounded-lg text-slate-400 hover:text-rose-600 dark:hover:text-rose-400 hover:bg-rose-50 dark:hover:bg-rose-950/50 border border-slate-200 dark:border-slate-700 transition"
                            title="Delete Schedule"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
